"""
Aegis PQC — ECDAT service adapter.

A thin orchestration layer between the GUI and the ECDAT backend. It runs the
established pipeline in order and returns the results; it contains **no
discovery, risk, recommendation, or prioritisation logic of its own**. Every
number the GUI shows comes from a backend module through this adapter.

    discovery adapters
          ↓
    inventory  (context resolution)
          ↓
    cbom · quantum_risk · recommendations · migration_priority
          ↓
    PipelineResult  ← one object the GUI reads

WHY THIS EXISTS
---------------
The GUI must not call five backends and join them itself — that would put
business logic in the presentation layer. This adapter does the joining once,
deterministically, so the GUI is pure presentation and the backend stays the
single source of truth.

SAFETY
------
Runs only the backends, which are themselves execution-free. It adds no
subprocess, network, or filesystem behaviour beyond the discovery scanners'
own Phase 1–5 safety boundaries. The demo estate is generated by the existing
fixtures, never recreated here.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from backend import (
    cbom,
    demo_binaries,
    demo_enterprise,
    demo_manifests,
    demo_source,
    inventory,
    migration_priority as mp,
    quantum_risk as qr,
    recommendations as rec,
)
from backend.discovery import ScanLimits, binary, certificates, dependencies, source
from backend.discovery.attribution import ComponentResolver, extract_declared_paths
from backend.model import (
    ApplicationContext,
    CryptoFinding,
    MigrationPriority,
    MigrationPriorityResult,
    QuantumRiskResult,
    RecommendationResult,
)

#: Demo applications, for the GUI's demo-mode affordance. Names only — the
#: fixtures own their contents.
DEMO_APPLICATIONS = (
    "payments-api",
    "legacy-auth",
    "mobile-gateway",
    "pqc-pilot",
    "content-portal",
)


@dataclass(slots=True)
class PipelineResult:
    """Everything the GUI needs from one ECDAT run.

    Findings, risk results, recommendations, and priorities are aligned by
    ``finding_id``. The roadmap and CBOM are derived views. The policy and
    contexts are carried so the GUI can show assumptions with provenance.
    """

    target: str
    findings: list[CryptoFinding] = field(default_factory=list)
    risks: list[QuantumRiskResult] = field(default_factory=list)
    recommendations: list[RecommendationResult] = field(default_factory=list)
    priorities: list[MigrationPriorityResult] = field(default_factory=list)
    roadmap: dict[str, list[dict[str, Any]]] = field(default_factory=dict)
    contexts: dict[str, ApplicationContext] = field(default_factory=dict)
    policy: qr.RiskPolicy | None = None
    errors: list[str] = field(default_factory=list)

    @property
    def is_empty(self) -> bool:
        return not self.findings


# ==========================================================================
# Demo estate
# ==========================================================================


def build_demo_estate(root: Path) -> Path:
    """Materialise the full demo estate using the existing fixtures.

    Reuses every Phase 1–5 fixture and appends the risk-policy block the
    quantum-risk engine reads. The estate is never recreated here — this only
    calls the fixtures and stitches the policy.

    Returns:
        The estate root.
    """
    demo_enterprise.generate(root, force=True)
    demo_manifests.write_application_manifests(root)
    demo_source.write_application_source(root)
    demo_binaries.write_application_binaries(root)

    policy_path = root / "aegis_policy.yaml"
    existing = policy_path.read_text(encoding="utf-8") if policy_path.exists() else ""
    if "quantum_risk:" not in existing:
        policy_path.write_text(
            existing + "\nquantum_risk:\n  crqc_horizon_years: 10\n"
            "  default_migration_years: 3\n",
            encoding="utf-8",
        )
    return root


# ==========================================================================
# Pipeline
# ==========================================================================


def run_pipeline(
    target: Path,
    surfaces: tuple[str, ...] = ("certificates", "dependencies", "source", "binary"),
    limits: ScanLimits | None = None,
) -> PipelineResult:
    """Run the full ECDAT pipeline over a target directory.

    Args:
        target: Estate or repository root to scan.
        surfaces: Which discovery surfaces to run. Defaults to the four on-disk
            surfaces (container scanning takes an archive, handled separately).
        limits: Optional scan limits, passed through to the adapters.

    Returns:
        A :class:`PipelineResult` with every stage's output aligned by finding
        id. A missing target yields a result carrying an error, not an
        exception.
    """
    target = Path(target)
    result = PipelineResult(target=str(target))

    if not target.exists():
        result.errors.append(f"Target does not exist: {target}")
        return result

    policy_map = inventory.load_policy(target)
    raw_policy = inventory._parse_policy_file(target / "aegis_policy.yaml")
    resolver = ComponentResolver(extract_declared_paths(raw_policy))
    result.policy = qr.load_risk_policy(target)

    # --- discovery ---
    findings: list[CryptoFinding] = []
    if "certificates" in surfaces:
        scan = certificates.CERTIFICATE_ADAPTER.scan(target, "ecdat", limits)
        findings.extend(scan.findings)
        result.errors.extend(f"certificates: {e}" for e in scan.errors)
    if "dependencies" in surfaces:
        scan = dependencies.DEPENDENCY_ADAPTER.scan(target, "ecdat", limits, resolver=resolver)
        findings.extend(scan.findings)
        result.errors.extend(f"dependencies: {e}" for e in scan.errors)
    if "source" in surfaces:
        scan = source.SOURCE_ADAPTER.scan(target, "ecdat", limits, resolver=resolver)
        findings.extend(scan.findings)
        result.errors.extend(f"source: {e}" for e in scan.errors)
    if "binary" in surfaces and binary.LIEF_AVAILABLE:
        scan = binary.BINARY_ADAPTER.scan(target, "ecdat", limits, resolver=resolver)
        findings.extend(scan.findings)
        result.errors.extend(f"binary: {e}" for e in scan.errors)

    result.findings = findings
    if not findings:
        return result

    # --- context resolution ---
    result.contexts = {
        component: inventory.resolve_context(component, policy_map)
        for component in {f.component for f in findings if f.component}
    }

    # --- assessment chain (each stage consumes the previous) ---
    result.risks = qr.assess_inventory(findings, result.contexts, result.policy)
    result.recommendations = rec.recommend_batch(findings, result.risks)
    result.priorities = mp.prioritize_batch(result.recommendations, result.contexts)
    result.roadmap = mp.build_roadmap(result.priorities, result.recommendations)

    return result


# ==========================================================================
# Derived views for the GUI (pure, testable)
# ==========================================================================


def overview_metrics(result: PipelineResult) -> dict[str, int]:
    """Headline counts for the Overview surface, all backend-derived."""
    by_source: dict[str, int] = {}
    for finding in result.findings:
        by_source[finding.source_type.value] = by_source.get(finding.source_type.value, 0) + 1

    risk_summary = qr.risk_summary(result.risks)
    priority_summary = mp.summarize(result.priorities)

    return {
        "total_findings": len(result.findings),
        "components": len({f.component for f in result.findings if f.component}),
        "certificates": by_source.get("certificate_file", 0),
        "dependencies": by_source.get("dependency", 0),
        "source_findings": by_source.get("source_code", 0),
        "binary_findings": by_source.get("binary", 0),
        "container_findings": by_source.get("container", 0),
        "quantum_vulnerable": risk_summary["by_quantum_category"].get("quantum_vulnerable", 0),
        "post_quantum": risk_summary["by_quantum_category"].get("post_quantum", 0),
        "capability_only": risk_summary["by_quantum_category"].get("capability_only", 0),
        "immediate": priority_summary["by_priority"].get("immediate", 0),
        "actionable": priority_summary["actionable"],
    }


def cbom_document(result: PipelineResult) -> str:
    """The CycloneDX CBOM for the current findings. Delegates to Phase 6."""
    return cbom.generate_cbom(result.findings)


def cbom_stats(result: PipelineResult) -> dict[str, int]:
    """Component/library counts for the CBOM surface, from the generated CBOM."""
    import json

    document = cbom.generate_cbom(result.findings)
    parsed = json.loads(document)
    components = parsed.get("components", [])

    crypto_assets = sum(1 for c in components if c.get("type") == "cryptographic-asset")
    libraries = sum(1 for c in components if c.get("type") == "library")
    capability_only = 0
    for component in components:
        for prop in component.get("properties", []):
            if prop.get("name") == "aegis:capability_only" and prop.get("value") == "true":
                capability_only += 1
                break

    return {
        "components": len(components),
        "crypto_assets": crypto_assets,
        "libraries": libraries,
        "capability_only": capability_only,
    }


def risk_by_finding(result: PipelineResult) -> dict[str, QuantumRiskResult]:
    """Index the risk results by finding id, for detail joins."""
    return {r.finding_id: r for r in result.risks}


def recommendation_by_finding(result: PipelineResult) -> dict[str, RecommendationResult]:
    """Index the recommendations by finding id, for detail joins."""
    return {r.finding_id: r for r in result.recommendations}


def priority_by_finding(result: PipelineResult) -> dict[str, MigrationPriorityResult]:
    """Index the priorities by finding id, for detail joins."""
    return {p.finding_id: p for p in result.priorities}


def migration_items(result: PipelineResult) -> list[MigrationPriorityResult]:
    """Actionable migration items only — NO_ACTION excluded, as it is not work."""
    return [
        p for p in result.priorities if p.priority is not MigrationPriority.NO_ACTION
    ]


def assumptions_view(result: PipelineResult) -> list[dict[str, Any]]:
    """The configured assumptions with provenance, for the Settings surface."""
    if result.policy is None:
        return []
    policy = result.policy
    rows = [
        ("CRQC horizon", policy.crqc_horizon_years, policy.source),
        ("Default migration time", policy.default_migration_years, policy.source),
        ("Default data lifetime", policy.default_data_lifetime_years, policy.source),
    ]
    return [
        {
            "name": name,
            "value": f"{value:g} years" if value is not None else "not configured",
            "provenance": provenance if value is not None else "missing",
        }
        for name, value, provenance in rows
    ]


def context_view(result: PipelineResult) -> list[dict[str, Any]]:
    """Declared organisation context per component, with provenance."""
    rows: list[dict[str, Any]] = []
    for component in sorted(result.contexts):
        context = result.contexts[component]
        rows.append(
            {
                "component": component,
                "data_lifetime_years": context.data_lifetime_years,
                "data_sensitivity": context.data_sensitivity.value,
                "business_criticality": context.business_criticality.value,
                "provenance": context.context_source.value,
                "is_declared": context.is_declared,
            }
        )
    return rows
